# Example configuration file for prometheus-swift-exporter
# Copyright (C) 2016 Canonical, Ltd.
#

listen_port: 9183
cloud: mycloud

# Number of seconds to wait before timing out when calling
# the Swift recon API
api_timeout: 10

# The number of asynchronous workers to use when connecting to
# the Swift recon API
api_threads: 10

# Port for swift recon urls
swift_port: 6000

# There is no way to retrieve them using OpenStack APIs
# For clouds deployed without swift, remove this part
swift_hosts:
    - host1.example.com
    - host2.example.com
